// @ts-ignore Generated by the OpenNext build before Wrangler bundles this entrypoint.
import openNextWorker from "./.open-next/worker.js";
import catalog from "./lib/calendar/generated/catalog-5787.json";

interface WorkerEnvironment {
  SITE_URL: string;
  ADMIN_API_TOKEN: string;
}

const CAMPAIGN_PREFIX = "/high-holidays";
const PUBLIC_PATHS = new Set([
  "",
  "/about",
  "/basket",
  "/basket/confirmation",
  "/confirmation",
  "/contact",
  "/expired",
  "/find",
  "/icon.svg",
  "/privacy",
  "/refunds",
  "/terms",
  "/robots.txt",
  "/sitemap.xml",
]);
const CATALOG_PATHS = new Set<string>();
for (const minyan of catalog.minyanim) CATALOG_PATHS.add(`/${minyan.slug}`);
for (const item of catalog.items) {
  CATALOG_PATHS.add(`/${item.minyan}/${item.occasion}`);
  CATALOG_PATHS.add(`/${item.minyan}/${item.occasion}/${item.slug}`);
}

function isUnknownPublicPath(pathname: string): boolean {
  if (!pathname.startsWith(CAMPAIGN_PREFIX)) return false;
  const relative = pathname.slice(CAMPAIGN_PREFIX.length).replace(/\/$/, "");
  if (PUBLIC_PATHS.has(relative) || CATALOG_PATHS.has(relative)) return false;
  return !["/api/", "/admin", "/_next/", "/images/"].some(
    (prefix) => relative === prefix.replace(/\/$/, "") || relative.startsWith(prefix)
  );
}

export default {
  async fetch(request: Request, env: WorkerEnvironment, ctx: ExecutionContext) {
    const url = new URL(request.url);
    if (url.pathname === "/robots.txt") {
      return new Response(
        [
          "User-agent: *",
          "Allow: /",
          "Disallow: /high-holidays/admin/",
          "Disallow: /high-holidays/confirmation",
          "Disallow: /high-holidays/basket/confirmation",
          "Sitemap: https://ponevez.com/high-holidays/sitemap.xml",
          "",
        ].join("\n"),
        { headers: { "content-type": "text/plain; charset=utf-8" } }
      );
    }
    const response = await openNextWorker.fetch(request, env, ctx);
    if (response.status === 200 && isUnknownPublicPath(url.pathname)) {
      return new Response(response.body, {
        status: 404,
        statusText: "Not Found",
        headers: response.headers,
      });
    }
    return response;
  },

  scheduled(
    _controller: ScheduledController,
    env: WorkerEnvironment,
    ctx: ExecutionContext
  ) {
    const maintenanceUrl = new URL("/high-holidays/api/admin/maintenance", env.SITE_URL);
    const request = new Request(maintenanceUrl, {
      method: "POST",
      headers: { "x-admin-token": env.ADMIN_API_TOKEN },
    });
    ctx.waitUntil(
      openNextWorker.fetch(request, env, ctx).then(async (response: Response) => {
        if (!response.ok) {
          console.error(
            `Scheduled maintenance failed (${response.status}): ${await response.text()}`
          );
        }
      })
    );
  },
};
