export const keys = {
  hold: (kibbudId: string) => `hold:${kibbudId}`,
  sold: (kibbudId: string) => `sold:${kibbudId}`,
  pending: (kibbudId: string) => `pending:${kibbudId}`,
  pledge: (pledgeId: string) => `pledge:${pledgeId}`,
  checkout: (paymentId: string) => `checkout:${paymentId}`,
  checkoutByHold: (holdToken: string) => `checkout:hold:${holdToken}`,
  order: (orderId: string) => `order:${orderId}`,
  paymentEventLock: (eventId: string) => `payment:event-lock:${eventId}`,
  paymentEventDone: (eventId: string) => `payment:event-done:${eventId}`,
  email: (emailId: string) => `email:${emailId}`,
  pendingPledges: "pledges:pending",
  orders: "orders",
  emailOutbox: "emails:outbox",
} as const;
